name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [14,18]
        os-version: [ubuntu-latest]
    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Get-Code
        uses: actions/checkout@v3

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Build
        run: npm run build