name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12,16,18]
        os-version: [ubuntu-latest]
        include:
          - node-version: 20
            os-version: ubuntu-latest
            npm: 6
        execlude:
          - node-version: 12
            os-version: ubuntu-latest
    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Get-Code
        uses: actions/checkout@v3

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Build
        run: npm run build