name: Events
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
  workflow_dispatch:
jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: print github event context value with toJSON Expression
        run: echo "${{ toJSON(github.event)}}"