name: Pull Events
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
    branches:
      - main
      - feature/**
  workflow_dispatch:
jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: print github event context value with toJSON Expression
        run: echo "${{ toJSON(github.event)}}"