name: Push Events
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
    branches:
      - main
      - feature/**
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - '.github/workflows/*'
    
    # you may only define one of `paths` and `paths-ignore` for a single event
    # paths:
    #   - '**.js'
  workflow_dispatch:
jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: print github event context value with toJSON Expression
        run: echo "${{ toJSON(github.event)}}"